##########################################################
# IMPORTANT: before deploying apps, ensure that 'regcred'#
# image pull secret and 'cloudsql-instance-credentials'  #
# secret are created in the namespace you want to use.   #
##########################################################

# metadata -- add as many key/value pairs as you want
[metadata]
org = "DNT"
maintainer = "Roar Skår  & Sami Alajrami (sami@praqma.com)"

# paths to the certificate for connecting to the cluster
# You can skip this if you use Helmsman on a machine with kubectl already connected to your k8s cluster.
[certificates]
caCrt    = "$PROD_CLUSTER_CA_CERT"
caKey    = "$PROD_CLUSTER_CA_KEY"
caClient = "$PROD_CLUSTER_CLIENT_CERT"

[settings]
kubeContext = "dnt" # will try connect to this context first, if it does not exist, it will be created using the details below
username = "dnt-prod-admin"
password = "$PROD_CLUSTER_PASSWORD" # admin user password
clusterURI = "$PROD_CLUSTER_URI" # cluster API
slackWebhook = "$SLACK_WEBHOOK_HELMSMAN"


# define your environments and thier k8s namespaces
# syntax: environment_name = "k8s_namespace"
[namespaces]
[namespaces.production]



# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
[helmRepos]
dnt = "gs://dnt-helm-repo"

# define the desired state of your applications helm charts
# each contains the following:

[apps]
    # Verdandi's ingress is defined by Urdr. Thus, Urdr must be deployed for Verdandi's ingress to be available.
    [apps.verdandi]
    name = "verdandi" # should be unique across all apps
    description = "Verdandi Production App."
    namespace = "production" # maps to the namespace as defined in environmetns above
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "dnt/verdandi" # changing the chart name means delete and recreate this chart
    version = "0.2.0"
    valuesFile = "verdandi-production-values.yaml"
    protected = true
    [apps.verdandi.set]
    "containers[1].environment.MONGO_URI" = "$VERDANDI_MONGO_URI"